version: "3.9"
services:
  be:
    build: be
    ports:
      - "3050:3000"
    environment:
      - PORT=3000
  fe:
    build: fe
    ports:
      - "3040:3000"
    environment:
      - PORT=3000
      - VITE_API_URL=http://localhost:3050
